version: "3.7"

services:
  directus:
    image: directus/directus:latest
    container_name: directus
    ports:
      - 8055:8055
    volumes:
      - directus_database:/directus/database
      - directus_uploads:/directus/uploads
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8055/server/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 10

  initialize-db:
    image: alpine:latest
    container_name: initDb
    volumes: 
      - ./scripts:/scripts
    environment:
      DIRECTUS_URL: "http://directus:8055"
      ADMIN_ACCESS_TOKEN: $DIRECTUS_TOKEN
    command: >
      /bin/sh -c '
        apk add curl jq bash
        until curl -s http://directus:8055/server/health | grep -q "ok"; do
          echo "Waiting for directus to be ready..."
          sleep 5
        done
        /bin/bash ./scripts/directus/build-tables.sh
      '


volumes:
  directus_database:
  directus_uploads:
