version: '3.7'

services:
  reminderbot:
    container_name: reminderbot
    image: jasoncky96/telegram-reminderbot:latest
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    restart: always
    networks:
      - reminderbot
    environment:
      BOT_TOKEN: $BOT_TOKEN
      MODE: PRODUCTION
      DEV_CHAT_ID: $DEV_CHAT_ID
      
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_DB: $MONGO_DB
      MONGO_SERVER: db
      MONGO_PORT: 27017    
    depends_on: 
      - db 

  reminderbot_pollserver:
    container_name: reminderbot_pollserver
    image: jasoncky96/telegram-pollingserver:latest
    restart: always
    networks:
      - reminderbot
    environment:
      MODE: PRODUCTION
      BOT_TOKEN: $BOT_TOKEN
      DEV_CHAT_ID: $DEV_CHAT_ID
      POLLING_INTERVAL: "0.2"
      APP_SERVER: reminderbot
    depends_on: 
      - reminderbot
      - db 

  db:
    image: mongo:4.4.9-focal
    container_name: reminderbot_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - type: volume
        source: reminderbot-db
        target: /data/db
    networks:
      - reminderbot

volumes:
  reminderbot-db:
    driver: local
    name: telegram-reminderbot_reminderbot-db

networks:
  reminderbot: