package main

import (
	"flag"

	_ "github.com/Jason-CKY/telegram-reminderbot/docs" // docs is generated by Swag CLI, you have to import it.
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"

	"github.com/Jason-CKY/telegram-reminderbot/pkg/core"
	"github.com/Jason-CKY/telegram-reminderbot/pkg/utils"
	"github.com/joho/godotenv"
	log "github.com/sirupsen/logrus"
)

func main() {
	// Load environment variables from .env file
	err := godotenv.Load()

	if err != nil {
		log.Infof("Error loading .env file: %v\nUsing environment variables instead...", err)
	}

	flag.StringVar(&core.LogLevel, "log-level", utils.LookupEnvOrString("LOG_LEVEL", core.LogLevel), "Logging level for the server")
	flag.StringVar(&core.DirectusHost, "fpath", utils.LookupEnvOrString("DIRECTUS_HOST", core.DirectusHost), "Hostname for directus server")
	flag.StringVar(&core.BotToken, "bot-token", utils.LookupEnvOrString("TELEGRAM_BOT_TOKEN", core.BotToken), "Bot token for telegram bot")

	flag.Parse()

	// setup logrus
	log.SetReportCaller(true)
	log.SetFormatter(&log.TextFormatter{
		FullTimestamp:          true,
		DisableLevelTruncation: true,
	})
	logLevel, _ := log.ParseLevel(core.LogLevel)
	log.SetLevel(logLevel)

	log.Infof("connecting to directus at: %v", core.DirectusHost)

	bot, err := tgbotapi.NewBotAPI(core.BotToken)
	bot.Debug = true
	log.Printf("Authorized on account %s", bot.Self.UserName)

	if err != nil {
		log.Panic(err)
	}
	u := tgbotapi.NewUpdate(0)
	u.Timeout = 60
	updates := bot.GetUpdatesChan(u)

	for update := range updates {
		if update.Message != nil { // If we got a message
			log.Printf("[%s] %s", update.Message.From.UserName, update.Message.Text)

			msg := tgbotapi.NewMessage(update.Message.Chat.ID, update.Message.Text)
			msg.ReplyToMessageID = update.Message.MessageID

			bot.Send(msg)
		}
	}

}
