name: build-deploy

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: olegtarasov/get-tag@v2.1.3
        id: tagName
      - name: Build and push the image
        run: |
          docker login --username Jason-CKY --password ${{ secrets.GH_PAT }} ghcr.io
          docker build -f ./build/Dockerfile --tag ghcr.io/jason-cky/telegram-reminderbot:latest --target production .
          docker push ghcr.io/jason-cky/telegram-reminderbot:$GIT_TAG_NAME
          docker push ghcr.io/jason-cky/telegram-reminderbot:latest
